# Generated by Django 4.1.1 on 2023-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
